// <auto-generated />
using MauiSharedApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MauiSharedApp.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902114226_SeedCustomersAndSales")]
    partial class SeedCustomersAndSales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MauiSharedApp.API.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SalesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalesId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Tugu Yogyakarta",
                            Latitude = -7.7830000000000004,
                            Longitude = 110.36709999999999,
                            Name = "Toko Tugu Jaya",
                            SalesId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Keraton Yogyakarta",
                            Latitude = -7.8052000000000001,
                            Longitude = 110.36409999999999,
                            Name = "Batik Keraton",
                            SalesId = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "Malioboro Street",
                            Latitude = -7.7925000000000004,
                            Longitude = 110.36539999999999,
                            Name = "Toko Oleh-Oleh Malioboro",
                            SalesId = 1
                        },
                        new
                        {
                            Id = 4,
                            Address = "Candi Prambanan",
                            Latitude = -7.7519999999999998,
                            Longitude = 110.4915,
                            Name = "Warung Prambanan",
                            SalesId = 2
                        },
                        new
                        {
                            Id = 5,
                            Address = "Candi Borobudur",
                            Latitude = -7.6078999999999999,
                            Longitude = 110.2038,
                            Name = "Kios Borobudur",
                            SalesId = 2
                        },
                        new
                        {
                            Id = 6,
                            Address = "Pantai Parangtritis",
                            Latitude = -8.0252999999999997,
                            Longitude = 110.33159999999999,
                            Name = "Cafe Parangtritis",
                            SalesId = 2
                        });
                });

            modelBuilder.Entity("MauiSharedApp.API.Models.Sales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "budi.santoso@example.com",
                            Name = "Budi Santoso",
                            Phone = "081100000001"
                        },
                        new
                        {
                            Id = 2,
                            Email = "siti.rahayu@example.com",
                            Name = "Siti Rahayu",
                            Phone = "081100000002"
                        });
                });

            modelBuilder.Entity("MauiSharedApp.API.Models.Customer", b =>
                {
                    b.HasOne("MauiSharedApp.API.Models.Sales", "Sales")
                        .WithMany("Customers")
                        .HasForeignKey("SalesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("MauiSharedApp.API.Models.Sales", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
